/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Converter: typeof import('./src/components/Converter.vue')['default']
    ConverterDecimal: typeof import('./src/components/ConverterDecimal.vue')['default']
  }
}
